CREATE DATABASE customerdb;
USE customerdb;

-- running data from jupyter notebook
SELECT * FROM shopping_data;

-- Business Insights Question
-- Which Category generates highest Revenue?

select category, sum(purchase_amount) as highest_revenue
from shopping_data
group by category
order by highest_revenue desc
limit 1;

-- ? Business Problem : Company does not know which category contributes most to Revenue

-- Impact :-
          -- Helps prioritize high performing categories
          -- Optimizes Inventory Planning 
          -- Improves marketing ROI
-- Are Discounts actually increases purchase values?

select discount_applied,
round(sum(purchase_amount),2) as total_revenue,
round(avg(purchase_amount),2) as Average_amount
from shopping_data
group by discount_applied;

-- ? Business Problem : Discounts may reduce profits without increasing sales

-- Impact :-
          -- Identify effectiveness of discounts
          -- Reduce unnecessary discounts costs
          -- Improve profits margin

-- What is total revenue generated by male and female customer?

select gender,
       round(sum(purchase_amount),2) as total_revenue
from shopping_data
group by gender
order by total_revenue desc;

-- ? Business Problem : Lack of understanding of revenue contribution by gender segments.

-- Impact :-
          -- Helps design targeted marketing campaigns
          -- Improves customer segmentation strategy
          -- Enhances personalisation efforts
          
-- Which customer used a discount but still spent more than the average purchase amount?

select customer_id,
	   discount_applied,
       purchase_amount 
from shopping_data
where discount_applied = "Yes" and purchase_amount > (select avg(purchase_amount) from shopping_data)
order by purchase_amount desc
limit 10;

select
       customer_id,
	   discount_applied,
       purchase_amount 
from shopping_data
where discount_applied = "Yes" and purchase_amount > (select avg(purchase_amount) from shopping_data)
limit 10;

-- ? Business Problem : Company cannot identify high-spending customers who are also discount users

-- Impact :-
          -- Identifies premium discounts-sensitive customers
          -- Enables targeted discounts campaigns
          -- Improves customer retention and revenue

-- Which are the top/bottom 5 products with the highest average review rating?

select item_purchased,
       round(avg(review_rating),2) as Average_rating
from shopping_data
group by item_purchased
order by Average_rating desc
limit 5;

select item_purchased,
       round(avg(review_rating),2) as Average_rating
from shopping_data
group by item_purchased
order by Average_rating asc
limit 5;

-- ? Business Problem : No visibility into product performance based on customer satisfaction.

-- Impact:-
         -- Promotes high-performing products
         -- Improves low-rated products
         -- Enhances custoner experience
         
-- Average purchase : Standard vs Express shipping

select shipping_type,
       count(distinct customer_id) as order_placed,
       round(avg(purchase_amount),2) as Average_amount,
       round(sum(purchase_amount),2) as total_revenue
from shopping_data
-- where shipping_type = "Express" or shipping_type = "Standard"
group by shipping_type;

-- ? Business Problem : Unclear if faster shipping leads to higher spending

-- Impact :-
          -- Helps optimize shipping pricing strategy
          -- Encourages premium shipping adoption
          -- Increases average order values
          
-- Do subscribed customers spend more? Compare average speed and total revenue between subscribers and non-subscribers

select subscription_status,
       count(customer_id) as users,
       round(avg(purchase_amount),2) as Average_amount,
       round(sum(purchase_amount),2) as total_revenue
from shopping_data
group by subscription_status;

-- ? Business Problem : The effectiveness of subscription programs is unknown.
 
-- Impact :-
          -- Validates subscription model performance
          -- Improves customer loyalty programs
          -- Increases customer lifetime value (CLV)


-- Top 5 products with highest discount usage %

select item_purchased,
       count(item_purchased) as total_number_of_times_sold,
       count(case when discount_applied='Yes' then 1 end)as Number_of_times_sold_when_discount_applied,
       count(case when discount_applied = 'Yes' then 1 end) * 100.0 / count(*) as discount_percentage
from shopping_data
group by item_purchased
order by discount_percentage desc;

-- ? Business Problem: Some products may be overly dependent on discounts.

-- Impact :-
          -- Identifies discount-driven products
          -- Helps optimise pricing strategy
          -- Reduces profit margin loss
          
-- Segemnt customer into new, returning and loyal based on their total number of previous purchase and show the count of each segment.

select 
case 
    when previous_purchases = '0' then 'New Customer'
    when previous_purchases between 1 and 15 then 'Returning Customer'
else 'Loyal Customer'
end as customer_segment,
count(*) as customer_count
from shopping_data
group by case 
    when previous_purchases = '0' then 'New Customer'
    when previous_purchases between 1 and 15 then 'Returning Customer'
else 'Loyal Customer'
end;

-- ? Business Problem : Lack of customer segmentation leads to generic strategies

-- Impact :-
          -- Enables personalised marketing
          -- Improves retention strategies
          -- Increases conversion rates
          
-- What are the top 3 most purchased products within each category?

with cte as
(
select category,
       item_purchased,
       count(item_purchased) as Count_of_purchasing,
       rank() over (partition by category order by count(item_purchased) desc) as rnk
from shopping_data
group by item_purchased,category
)
select * from cte
where rnk <= 3;

-- ? Business Problem: The company doesn't know top-performing products within categories.

-- Impact :-
          -- Improves product placement & recommendations
          -- Helps inventory optimisation
          -- Increases sales through best-sellers
          
-- Are customers who are repeat buyers (more than 5 previous purchases) are likely to subscribes?

select 
       case
       when previous_purchases > 5 then 'Repeat buyers'
       else 'Normal Buyers'
       end as customer_type,
       subscription_status,
       count(*) as customer_count,
       count(*) * 100.0 /sum(count(*)) over (partition by case
       when previous_purchases > 5 then 'Repeat buyers'
       else 'Normal Buyers'
       end ) as percent
from shopping_data
group by case
		 when previous_purchases > 5 then 'Repeat Buyers'
         else 'Normal Buyers'
         end, subscription_status;
         
-- ? Business Problem: Unclear relationship between loyality and subscription

-- Impact :-
          -- Improves subscription targeting
          -- Increases conversion to paid programs
          -- increase customer retention strategy

-- What is the revenue contribution of each age group?

select 
      case 
          when age between 18 and 25 then '18-25'
          when age between 26 and 35 then '26-35'
          when age between 36 and 50 then '36-50'
          else '51+'
	  end as age_group,
      round(sum(purchase_amount),2) as total_revenue
from shopping_data
group by case
		  when age between 18 and 25 then '18-25'
          when age between 26 and 35 then '26-35'
          when age between 36 and 50 then '36-50'
          else '51+'
	  end
order by total_revenue desc;


-- ? Business Problem: No visibility into which age group contributes to more revenue


-- Impact :-
		  -- Enables age-based targeting
          -- Enhances marketing efficiency





